### ISSUE TITLE
Print all logs when assertions fail

### ISSUE THREAD

**Issue by csilvers** [thejerf/slogassert#4]
This is maybe more controversial, but something we've found very valuable at Khan Academy: if one of the log-matching assertions fails, in addition to saying exactly what assertion failed, list all the log messages.  This makes it obvious if the issue is the message wasn't logged at all, or was logged with slightly different Attrs, or has a typo-mismatch between the log-string and the testing-string, or something else.

For concreteness, the logrus+testify way we do it looks like this:
```
	entries := testLogger.AllEntries()
	for _, entry := range entries {
		if !strings.Contains(entry.Message, messageContains) { // messageContains is part of the assertion
			continue
		}
		for k, v := range dataIncludes { // dataIncludes is part of the assertion
			t.Require().Equalf(v, entry.Data[k],
				"log-entry %v had %v=%v, expected %v=%v",
				entry, k, entry.Data[k], k, v)
		}
		return
	}
	strEntries := []string{}
	for _, entry := range entries {
		strEntries = append(strEntries, fmt.Sprintf("%v", entry))
	}
	t.Require().Fail(
		"no log entry message contained %v, entries:\n%v",
		messageContains, strEntries)
```

**Comment by thejerf** [comment]
I believe the latest commit should cover everything you have discussed here, one way or another. (I went for the generic exposure of what was previously the filter function.)

I will continue using this myself and gaining experience, and if you find something you're really heavily using, please feel free to open an issue with a suggested inclusion of a convenience method into this library. Otherwise, you should have all the tools you need for the things you encounter now. (And I have what I need for my "maybe we logged this, maybe not" case now.)

I'm closing these issues as an indication that I believe I've resolved the issue, and if the project owner doesn't close the issues they stay open forever :),  but by all means please re-open them if you disagree and want to continue the conversation. I'm pleased to be working with a real user giving this a solid workout.

**Comment by csilvers** [comment]
> I'm closing these issues as an indication that I believe I've resolved the issue, and if the project owner doesn't close the issues they stay open forever :), but by all means please re-open them if you disagree and want to continue the conversation. I'm pleased to be working with a real user giving this a solid workout.

I'm a bit reluctant to re-open this issue just to say thank you!, but I'm doing it anyway.  The new API looks really great to me.  I think it will make it easy to implement everything we need to (I had forgotten to mention the AssertMessageRegex use case we have :-) ), and it looks really clean.  I also appreciate how quickly this was all resolved.

We don't know what the timeframe is for us actually doing the work to migrate off logrus, but if new observations come up using this library we'll be sure to share them!

**Comment by csilvers** [comment]
(Oh, commenting doesn't automatically reopen.  Whew.)
