### ISSUE TITLE
Adding `slogassert.NewDefault(*testing.T) *Handler` to simplify usage

### ISSUE THREAD

**Issue by alecsammon** [thejerf/slogassert#6]
This library has really helped us with the migration to slog, and ensuring in tests that are log messages are still working as expected.

I've found I'm duplicating the following code, or having to build my own helpers to do it. This will setup `slogtest` with the default settings, and then restore it once the test is complete. 

```
handler := slogassert.New(t, slog.LevelDebug, nil)
origLogger := slog.Default()
origFlags := log.Flags()
t.Cleanup(func() {
	handler.AssertEmpty()

        log.SetOutput(os.Stdout)
        log.SetFlags(origFlags)
        slog.SetDefault(origLogger)
})
logger := slog.New(handler)
slog.SetDefault(logger)
```

Would you be open to me creating a PR to add this `slogassert.NewDefault(*testing.T, slog.Leveler) *Handler` that would do the above steps to simplify the usage in this case, and keep tests clean?

If we could add the `level` and `wrapped` options as a function option with `slogassert.NewDefault(*testing.T, ...Option)` then this would maintain functionality, but simplify usage for those who don't need it. Would also give the ability to add more functionality in the future without making breaking changes.

n.b. resetting the default logger isn't very easy!  If the original one is the default, then slog has protection to prevent it being written back again. Setting the output and flags directly is a little bit of a hack, but is probably good enough for all but very custom cases - and unlikely to affect anyone using this library in tests.

This is also not safe when using `t.Parallel()` - but a comment in the method declaration may be enough to highlight this.

**Comment by thejerf** [comment]
This does seem like a good place for functional options. I'm actually not a huge fan of the pattern, but the zero value of Level being a legal and common level makes it hard to have a convenient "null" value otherwise, and once you've got one functional option you've got them all.

I have found you can't force the AssertEmpty on people; it's too restrictive as code scales up. But you could make that a functional option, for convenience. Defaulting to not setting it, I think though. Documenting that it doesn't work with .Parallel is fine and I for one am fine about explaining exactly why right in the docs :)

**Comment by alecsammon** [comment]
Great - thank you.

I'll open a PR in the next few days for you to have a look at. Will use your suggestions - sound sensible to me.

**Comment by alecsammon** [comment]
I've opened a PR here: https://github.com/thejerf/slogassert/pull/7

Keen to hear your thoughts

Thanks
